export const ROOT_ROUTE_CHANGED = 'ROOT_ROUTE_CHANGED'
export const TAB_ROUTE_CHANGED = 'TAB_ROUTE_CHANGED'

export const GAME_NEXT = 'GAME_NEXT'
export const GAME_COMPLETED = 'GAME_COMPLETED'

export const PUZZLE_ACTIVE = 'PUZZLE_ACTIVE'
export const PUZZLE_NEXT = 'PUZZLE_NEXT'
export const PUZZLE_SOLVED = 'PUZZLE_SOLVED'
